mnist:
  input_dim: 784
  hidden_dims: [240, 240, 240, 240, 240, 240, 240]

cifar10:
  input_dim: 3072
  hidden_dims: [1000, 1000, 1000]

output_dim: 10

batch_size: 128
epochs: 50
forward_lr: 1e-3
inverse_lr: 3e-3
eta_hat: 0.05
sigma: 0.4
num_workers: 0
k_g_updates: 5

out_dir: dtp_checkpoints

log_interval: 100
checkpoint_interval: 10

dataset: mnist
